src/Berkman/SlideshowBundle/Entity/Repo.php
<?php

namespace Berkman\SlideshowBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Berkman\SlideshowBundle\Fetcher as Fetcher;

/**
 * Berkman\SlideshowBundle\Entity\Repo
 */
class Repo
{
    /**
     * @var string $id
     */
    private $id;

    /**
     * @var string $name
     */
    private $name;

	/**
	 * @var Berkman\SlideshowBundle\Fetcher $fetcher
	 */
	public $fetcher;

    /**
     * Set id
     *
     * @param string $id
     */
    public function setId($id)
    {
        $this->id = $id;
		$this->fetcher = $this->getFetcher(); 
    }

    /**
     * Get id
     *
     * @return string $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string $name
     */
    public function getName()
    {
        return $this->name . ' (' . $this->getId() . ')';
    }

	/**
	 * Get the fetcher object associated with this repo
	 *
	 */
	public function getFetcher()
	{
		$fetcher = null;

		if ($this->fetcher) {
			$fetcher = $this->fetcher;
		}
		else {
			//TODO: figure out a better way to do this stuff
			$className = '\\Berkman\\SlideshowBundle\\Fetcher\\'.$this->getId().'Fetcher';
			if (class_exists($className)) {
				$fetcher = new $className($this);
			}
			else {
				#throw some exception
			}
		}
		return $fetcher;
	}

	/**
	 * Get search results from this repo
	 *
	 * @param string $keyword
	 * @param int $startIndex
	 * @param int $endIndex
	 */
	public function fetchResults($keyword, $startIndex, $count)
	{
		return $this->getFetcher()->fetchResults($keyword, $startIndex, $count);
	}
    /**
     * @var datetime $created
     */
    private $created;

    /**
     * @var datetime $updated
     */
    private $updated;


    /**
     * Set created
     *
     * @param datetime $created
     */
    public function setCreated($created)
    {
        $this->created = $created;
    }

    /**
     * Get created
     *
     * @return datetime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param datetime $updated
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
    }

    /**
     * Get updated
     *
     * @return datetime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    public function getImportFormat()
    {
        return $this->getFetcher()->getImportFormat();
    }

    public function hasCustomImporter()
    {
        return $this->getFetcher()->hasCustomImporter();
    }
}

src/Berkman/SlideshowBundle/Entity/Slide.php
<?php

namespace Berkman\SlideshowBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Berkman\CatalogBundle\Entity\Image;

/**
 * Berkman\SlideshowBundle\Entity\Slide
 */
class Slide
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var integer $position
     */
    private $position;

    /**
     * @var Berkman\SlideshowBundle\Entity\Image
     */
    private $image;

    /**
     * @var Berkman\SlideshowBundle\Entity\Slideshow
     */
    private $slideshow;


    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set position
     *
     * @param integer $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    /**
     * Get position
     *
     * @return integer $position
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set image
     *
     * @param Berkman\SlideshowBundle\Entity\Image $image
     */
    public function setImage(Image $image)
    {
        $this->image = $image;
    }

    /**
     * Get image
     *
     * @return Berkman\SlideshowBundle\Entity\Image $image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set slideshow
     *
     * @param Berkman\SlideshowBundle\Entity\Slideshow $slideshow
     */
    public function setSlideshow(Slideshow $slideshow)
    {
        $this->slideshow = $slideshow;
        $this->position = count($this->getSlideshow()->getSlides()) + 1;
    }

    /**
     * Get slideshow
     *
     * @return Berkman\SlideshowBundle\Entity\Slideshow $slideshow
     */
    public function getSlideshow()
    {
        return $this->slideshow;
    }

    public function getThumbnailUrl()
    {
        return $this->getImage()->getThumbnailUrl();
    }

    /**
     * Create a slide from an Image
     *
     * @param Berkman\SlideshowBundle\Entity\Image $image
     */
    public function __construct(Image $image)
    {
        $this->setImage($image);
    }

    public function __call($functionName, $arguments)
    {
        return call_user_func_array(array($this->getImage(), $functionName), $arguments);
    }

}

src/Berkman/SlideshowBundle/Form/SlideshowType.php
<?php

namespace Berkman\SlideshowBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Doctrine\ORM\EntityRepository;

class SlideshowType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('name', null, array('label' => 'Slideshow Name'))
            ->add('description')
            ->add('slide_delay', null, array('label' => 'Slide Delay (seconds)'))
            ->add('always_show_info', 'checkbox', array('required' => false))
            ->add('display_controls', 'checkbox', array('required' => false))
            ->add('show_qr_code', 'checkbox', array('required' => false))
            ->add('published', 'checkbox', array('required' => false))
        ;

        if ($options['data']->getId()) {
            $slideshowId = $options['data']->getId();

            $builder->add('slides', null, array(
                'expanded' => true,
                'property' => 'thumbnailUrl',
                'query_builder' => function(EntityRepository $er) use ($slideshowId) {
                    return $er->createQueryBuilder('s')->where('s.slideshow = ?1')->orderBy('s.position', 'ASC')->setParameter(1, $slideshowId);
                }
            ));
        }
    }

    public function getName()
    {
        return 'slideshow';
    }
}

src/Berkman/SlideshowBundle/Controller/SlideshowController.php
<?php

namespace Berkman\SlideshowBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Berkman\SlideshowBundle\Entity\Slideshow;
use Berkman\SlideshowBundle\Entity\Slide;
use Berkman\CatalogBundle\Entity\Finder;
use Berkman\SlideshowBundle\Form\SlideshowType;
use Berkman\SlideshowBundle\Form\SlideshowChoiceType;
use Berkman\CatalogBundle\Form\Finder\MasterImportType;
use Berkman\SlideshowBundle\Fetcher\ImportFetcherInterface;

use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Acl\Domain\UserSecurityIdentity;
use Symfony\Component\Security\Acl\Permission\MaskBuilder;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Response;

/**
 * Slideshow controller.
 *
 */
class SlideshowController extends Controller
{
    /**
     * Finds and displays a Slideshow entity.
     *
     * @param integer $id  Slideshow id
     * @return Symfony Response
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Slideshow entity.');
        }

        $args = array(
            'entity'    => $entity,
            'canEdit'   => false,
            'canDelete' => false
        );

        $securityContext = $this->get('security.context');

        if  ($securityContext->isGranted('EDIT', $entity) === true) {
            $args['canEdit'] = true;
        }

        if ($securityContext->isGranted('DELETE', $entity) === true) {
            $deleteForm = $this->createDeleteForm($id);
            $args['canDelete'] = true;
            $args['delete_form'] = $deleteForm->createView();
        }

        return $this->render('BerkmanSlideshowBundle:Slideshow:show.html.twig', $args);
    }

    public function slideTilesAction($id)
    {
        $response = new Response();
        $response->setPublic();
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Slideshow entity.');
        }

        $updatedAt = $entity->getUpdated();
        $response->setLastModified($updatedAt);
        $response->setETag(md5($updatedAt->format('U')));

        if ($response->isNotModified($this->getRequest())) {

            return $response;
        } 
        else {
            $images = array();
            foreach ($entity->getSlides() as $slide) {
                $images[] = $slide->getImage();
            }
            return $this->render(
                'BerkmanSlideshowBundle:Slideshow:slideTiles.html.twig',
                array('images' => $images),
                $response
            );
        }
    }

    /**
     * Displays the actual slideshow
     *
     * @param integer $id  Slideshow id
     * @return Symfony Response
     */
    public function slideshowAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $response = new Response();
        $response->setPublic();

        $slideshow = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->find($id);

        if (!$slideshow) {
            throw $this->createNotFoundException('Unable to find Slideshow.');
        }

        $updatedAt = $slideshow->getUpdated();
        $response->setLastModified($updatedAt);

        if ($response->isNotModified($this->getRequest())) {
            return $response;
        }
        else {
            return $this->render(
                'BerkmanSlideshowBundle:Slideshow:slideshow.html.twig',
                array('slideshow' => $slideshow),
                $response
            );
        }
    }

    /**
     * Displays a form to create a new Slideshow entity.
     *
     * @return Symfony Response
     */
    public function newAction()
    {
        $entity = new Slideshow();
        $form   = $this->createForm(new SlideshowType(), $entity);

        return $this->render('BerkmanSlideshowBundle:Slideshow:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Creates a new Slideshow entity.
     *
     * @return Symfony Response
     */
    public function createAction()
    {
        $slideshow  = new Slideshow();
        $request = $this->getRequest();
        $form    = $this->createForm(new SlideshowType(), $slideshow);

        if ('POST' === $request->getMethod()) {
            $form->bindRequest($request);

            if ($form->isValid()) {
                $em = $this->getDoctrine()->getEntityManager();
                $user = $this->get('security.context')->getToken()->getUser();
                $slideshow->setPerson($user);
                $slideshow->setCreated(new \DateTime('now'));
                $finder = $this->getFinder();
                $catalogManager = $this->get('berkman_catalog.catalog_manager');

                if ($finder) {
                    $images = $finder->getSelectedImageResults();
                    foreach ($images as $image) {
                        $newImage = clone $image;
                        $newImage->setCatalog($image->getCatalog());
                        $slide = new Slide($newImage);
                        $slideshow->addSlide($slide);
                    }
                    $request->getSession()->remove('finder');
                }
                $slideshow->setUpdated(new \DateTime('now'));
                $em->persist($slideshow);
                $em->flush();
                $request->getSession()->setFlash('notice', 'New slideshow "' . $slideshow->getName() . '" created with ' . count($slideshow->getSlides()) . ' slides.');

                 // creating the ACL
                $aclProvider = $this->get('security.acl.provider');
                $objectIdentity = ObjectIdentity::fromDomainObject($slideshow);
                $acl = $aclProvider->createAcl($objectIdentity);

                // retrieving the security identity of the currently logged-in user
                $securityIdentity = UserSecurityIdentity::fromAccount($user);

                // grant owner access
                $acl->insertObjectAce($securityIdentity, MaskBuilder::MASK_OWNER);
                $aclProvider->updateAcl($acl);

                return $this->redirect($this->generateUrl('slideshow_show', array('id' => $slideshow->getId())));
            }
        }

        return $this->render('BerkmanSlideshowBundle:Slideshow:new.html.twig', array(
            'entity' => $slideshow,
            'form'   => $form->createView()
        ));
    }

    /**
     * Displays a form to edit an existing Slideshow entity.
     *
     * @param integer $id  Slideshow id
     * @return Symfony Response
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $slideOrder = array();

        $entity = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Slideshow entity.');
        }

        // check for edit access
        if (false === $this->get('security.context')->isGranted('EDIT', $entity))
        {
            throw new AccessDeniedException();
        }

        foreach ($entity->getSlides() as $slide) {
            $slideOrder[] = $slide->getImage()->getId();
        }

        $editForm = $this->createForm(new SlideshowType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BerkmanSlideshowBundle:Slideshow:edit.html.twig', array(
            'entity'      => $entity,
            'slide_order' => implode(',',$slideOrder),
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing Slideshow entity.
     *
     * @param integer $id  Slideshow id
     * @return Symfony Response
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $entity = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->find($id);

        $oldSlideIds = $entity->getSlides()->map(function ($slide) { return $slide->getId(); })->toArray();

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Slideshow entity.');
        }

        // check for update access
        if (false === $this->get('security.context')->isGranted('EDIT', $entity))
        {
            throw new AccessDeniedException();
        }

        $editForm   = $this->createForm(new SlideshowType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->getRequest();

        if ('POST' === $request->getMethod()) {
            $editForm->bindRequest($request);

            if ($editForm->isValid()) {
                $slideCatalog = $em->getRepository('BerkmanSlideshowBundle:Slide');
                $newSlideIds = $entity->getSlides()->map(function ($slide) { return $slide->getId(); })->toArray();
                $slideIdsToRemove = array_diff($oldSlideIds, $newSlideIds);

                if ($slideIdsToRemove) {
                    $slidesToRemove = $slideCatalog->findById($slideIdsToRemove);
                    foreach ($slidesToRemove as $slide) {
                        $em->remove($slide);
                    }
                }

                foreach (explode(',', $request->get('slide_order')) as $position => $slideId) {
                    $slide = $slideCatalog->find($slideId);
                    $slide->setPosition($position + 1);
                    $em->persist($slide);
                }
                

src/Berkman/SlideshowBundle/Resources/views/Slideshow/addImages.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}

{% block title %}Spectacle - Add Your Images to a Slideshow{% endblock %}

{% block body %}
<div id="slideshow-tabs">
    <ul>
        <li><a href="#add-images-container">ADD IMAGES</a></li>
    </ul>
    <div id="add-images-container">
        {% if images %}
        <div>
            <h2>Your images</h2>
            <div class="lightWrap">
            {% for image in images %}
            <a href="{{ image.recordUrl }}" target="_blank"><img src="{{ image.thumbnailUrl }}" alt="{{ image.id }}" /></a>
            {% endfor %}
            </div>
        </div>
        {% if app.user and app.user.slideshows|length > 0 %}
        <div>
            <h2>Add images to existing slideshow</h2>
            <div class="lightWrap">
            <form method="post" action="{{ path('slideshow_add_images') }}" {{ form_enctype(addImagesForm) }}>
                {{ form_widget(addImagesForm) }}
                <button type="submit">Add</button>
            </form>
            </div>
        </div>
        {% endif %}
        <div>
            <h2>{{ app.user.slideshows|length > 0 ? 'Or, create' : 'Create'}} a new slideshow</h2>
            <div class="lightWrap">
            {% include 'BerkmanSlideshowBundle:Slideshow:newForm.html.twig' %}
            </div>
        </div>
        {% else %}
        <h2>You have no selected images</h2>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts 'js/slideshow-add-images.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/Berkman/SlideshowBundle/Resources/views/Slideshow/edit.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}
{% form_theme edit_form 'BerkmanSlideshowBundle:Form:images.html.twig' %}

{% block title %}Spectacle - Edit Slideshow{% endblock %}
{% block body %}
<div id="slideshow-tabs">
    <ul>
        <li><a href="#edit-container">EDIT SLIDESHOW</a></li>
    </ul>
    <div id="edit-container">
        <a class="float-right buttoned" href="{{ path('slideshow_slideshow', { 'id': entity.id }) }}">Start Slideshow</a>
        <form id="edit" action="{{ path('slideshow_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
            {{ form_widget(edit_form) }}
            <input type="hidden" name="slide_order" value="{{ slide_order }}" id="slide_order" />
            <button type="submit">Update</button>
        </form>
        <form action="{{ path('slideshow_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
{% javascripts 'js/jquery-ui-1.8.16.custom.min.js' %}
<script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}
<script type="text/javascript">
$(function() {
    $('#slideshow-tabs').tabs();
    $( "#slideshow_slides" ).sortable({
        placeholder: 'placeholder',
        start: function(event, ui) {
            ui.placeholder.css({
                height: ui.item.outerHeight(),
                width: ui.item.outerWidth()
            });
        }
    });
    $( "#slideshow_slides" ).disableSelection();
    $('#edit').submit(function() {
        var order = [], id;
        $('li.image :checkbox:checked').each(function(i, elem) {
            id = $(elem).attr('id');
            order.push(id.substring(id.lastIndexOf('_') + 1));
        });
        $('#slide_order').val(order.toString());
    });
});
</script>
{% endblock %}

src/Berkman/SlideshowBundle/Resources/views/Slideshow/import.html.twig
<h3>Spectacle Importer</h3>
<div class="indented">
    <h4>Instructions</h4>
    <div class="indented">
        <p>
            Upload a CSV document with a line for each image, with each line having one of these formats:
        </p>
        <ul>
        {% for catalog in finder.catalogs %}
            <li>
                For images from the {{ catalog.name }} catalog:<br />
                "{{ catalog.id }}",{{ catalog.importFormat }}
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
<form action="{{ path('finder_master_import') }}" method="post" {{ form_enctype(masterImportForm) }}>
    <div class="import-form">
        {{ form_widget(masterImportForm) }}
        <input type="submit" value="Import" />
    </div>
</form>

<h3>Catalog Importers</h3>
<form action="{{ path('finder_custom_import') }}" method="post" {{ form_enctype(masterImportForm) }}>
<ul class="indented">
{% for child in customImportForm if child.vars.type is defined and child.vars.type == 'file' %}     
    {% set catalog = finder.getCatalog(child.vars.name) %}
        <li>
        <h4>{{ catalog.id }}</h4>
        <div class="indented">
            <h5>Instructions</h5>
            <p class="indented">
                {{ catalog.importInstructions }}
            </p>
        </div>
        {{ form_widget(child) }}
        </li>
{% endfor %}
</ul>
{{ form_rest(customImportForm) }}
<input type="submit" value="Import" />
</form>

src/Berkman/SlideshowBundle/Resources/views/Slideshow/new.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}

{% block title %}Spectacle - Create a New Slideshow{% endblock %}

{% block body %}
<h2>Slideshow creation</h2>
{% include 'BerkmanSlideshowBundle:Slideshow:newForm.html.twig' %}

<ul class="record_actions">
    <li>
        <a href="{{ path('slideshow') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/Berkman/SlideshowBundle/Resources/views/Slideshow/newForm.html.twig
<form action="{{ path('slideshow_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <button type="submit">Create</button>
</form>

src/Berkman/SlideshowBundle/Resources/views/Slideshow/show.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}

{% block title %}Spectacle - Show Slideshow "{{ entity.name }}"{% endblock %}

{% block body %}
    <div id="slideshow-tabs">
        <ul>
            <li><a href="#slideshow-container">Slideshow</a></li>
        </ul>
        <div id="slideshow-container">
            <div id="slideshow-tools">
                <div id="embed_wrap">
                    <a id="slideshow-start-button" class="buttoned" href="{{ path('slideshow_slideshow', { 'id': entity.id }) }}">Start Slideshow</a>
                    <span id="embed_text">Embed Code:</span>
                    <textarea id="embed_code" readonly="readonly">
                {{- '<iframe src="' ~ url('slideshow_slideshow', { 'id' : entity.id }) ~ '" width="400" height="300" frameborder="0"></iframe>' -}} 
                    </textarea>
                </div>
                <h2 id="slideshow-title">{{ entity.name }}</h2>
                <dl>
                <dt>Creator:</dt><dd>{{ entity.person.username }}</dd>
                {% if entity.description is not empty %}
                    <dt>Description:</dt><dd>{{ entity.description }}</dd>
                {% endif %}
                </dl>
                {% if canEdit %}
                    <a class="buttoned" href="{{ path('slideshow_edit', { 'id': entity.id }) }}">Edit</a>
                {% endif %}
                {% if canDelete %}
                    <form action="{{ path('slideshow_delete', { 'id': entity.id }) }}" method="post">
                        {{ form_widget(delete_form) }}
                        <button type="submit">Delete</button>
                    </form>
                {% endif %}
            </div>
            {% render 'BerkmanSlideshowBundle:Slideshow:slideTiles' with { 'id': entity.id }, { 'standalone' : true } %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts 'js/slideshow-show.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/Berkman/SlideshowBundle/Resources/views/Slideshow/slideTiles.html.twig
{% import "BerkmanSlideshowBundle::macros.html.twig" as macros %}

{% if images is defined %}
{{ macros.show_images(images, 'ol') }}
{% endif %}

src/Berkman/SlideshowBundle/Resources/views/Slideshow/slideshow.html.twig
<!DOCTYPE html>
<html>
	<head>
		<title>Spectacle - {{ slideshow.name }}</title>
		{% stylesheets 'css/supersized.css'
					   'css/supersized.shutter.css'
	   %}
		<link rel="stylesheet" type="text/css" media="screen" href="{{ asset_url }}" />
		{% endstylesheets %}
		<link href='http://fonts.googleapis.com/css?family=Lato:400,900&v2' rel='stylesheet' type='text/css'>
	</head>
	<body>

        <div id="metadata-wrap">
            <div id="metadata"></div>
            <div id="toggle-metadata">Info <span id="toggle-metadata-icon">&#9660;</span></div>
        </div>

        {% if slideshow.showQrCode %}
        <div id="qr-code-wrap">
            <img id="qr-code" src="" />
        </div>
        {% endif %}

		<!--Thumbnail Navigation-->
		<div id="prevthumb"></div>
		<div id="nextthumb"></div>
		
		<!--Arrow Navigation-->
		<a id="prevslide" class="load-item hideable-button"></a>
		<a id="nextslide" class="load-item hideable-button"></a>
		
		<div id="thumb-tray" class="load-item">
			<div id="thumb-back"></div>
			<div id="thumb-forward"></div>
		</div>
		
		<!--Time Bar-->
		<div id="progress-back" class="load-item">
			<div id="progress-bar"></div>
		</div>
		
		<!--Control Bar-->
		<div id="controls-wrapper" class="load-item">
			<div id="controls">
				
				<a id="play-button"><img id="pauseplay" src="../../../images/pause.png"/></a>
			
				<!--Slide counter-->
				<div id="slidecounter">
					<span class="slidenumber"></span> / <span class="totalslides"></span>
				</div>
				
				<!--Slide captions displayed here-->
				<div id="slidecaption"></div>
				
				<!--Thumb Tray button-->
				<a id="tray-button"><img id="tray-arrow" src="../../../images/button-tray-up.png"/></a>
				
				<!--Navigation-->
				<ul id="slide-list"></ul>
				
			</div>
		</div>

		{% javascripts 'js/jquery-1.6.2.js'	
						'js/jquery.easing.min.js'
						'js/supersized.3.2.4.js'
						'js/supersized.shutter.js'
		%}
		<script src="{{ asset_url }}" type="text/javascript"></script>
		{% endjavascripts %}
		<script type="text/javascript">
			var slideshow_slides = [
				{% for slide in slideshow.slides %}
					{
						image: '{{ slide.Url|raw }}',
                        thumb: '{{ slide.thumbnailUrl|raw }}',
						url: '{{ slide.recordUrl|raw }}',
                        qrCodeUrl: '{{ slide.qrCodeUrl|raw }}',
						metadata: {
							{% for key, value in slide.metadata %}
							'{{ key }}': '{{- value -}}' {{ not loop.last ? ',' : '' }}
							{% endfor %}
						}
					}{{ not loop.last ? ',' : '' }}
				{% endfor %}
			];

			jQuery(function($){
				$.supersized({
				
					// Functionality
					slideshow               :   1,			// Slideshow on/off
					autoplay				:	1,			// Slideshow starts playing automatically
					start_slide             :   1,			// Start slide (0 is random)
					stop_loop				:	0,			// Pauses slideshow on last slide
					random					: 	0,			// Randomize slide order (Ignores start slide)
					slide_interval          :   {{ slideshow.slideDelay }} * 1000,		// Length between transitions
					transition              :   1, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
					transition_speed		:	1000,		// Speed of transition
					new_window				:	1,			// Image links open in new window/tab
					pause_hover             :   0,			// Pause slideshow on hover
					keyboard_nav            :   1,			// Keyboard navigation on/off
					performance				:	1,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
					image_protect			:	1,			// Disables image dragging and right click with Javascript
															   
					// Size & Position						   
					min_width		        :   0,			// Min width allowed (in pixels)
					min_height		        :   0,			// Min height allowed (in pixels)
					vertical_center         :   1,			// Vertically center background
					horizontal_center       :   1,			// Horizontally center background
					fit_always				:	1,			// Image will never exceed browser width or height (Ignores min. dimensions)
					fit_portrait         	:   1,			// Portrait images will not exceed browser height
					fit_landscape			:   0,			// Landscape images will not exceed browser width
                    animate_y_change        :   0,
															   
					// Components							
					slide_links				:	'blank',	// Individual links for each slide (Options: false, 'number', 'name', 'blank')
					thumb_links				:	1,			// Individual thumb links for each slide
					thumbnail_navigation    :   0,			// Thumbnail navigation
					slides 					:  	slideshow_slides,
												
					// Theme Options			   
					progress_bar			:	1,			// Timer for each slide							
					mouse_scrub				:	0,
                    show_controls			:	{{ slideshow.displayControls ? '1' : '0' }},
                    always_show_meta        :   {{ slideshow.alwaysShowInfo ? '1' : '0' }},
                    show_qr_code            :   {{ slideshow.showQrCode ? '1' : '0' }},
                    hide_metadata_height    :   500,
                    control_hide_delay      :   0
				});
			});
		</script>
	</body>
</html>