src/Berkman/SlideshowBundle/Entity/Slide.php
<?php

namespace Berkman\SlideshowBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Berkman\CatalogBundle\Entity\Image;

/**
 * Berkman\SlideshowBundle\Entity\Slide
 */
class Slide
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var integer $position
     */
    private $position;

    /**
     * @var Berkman\SlideshowBundle\Entity\Image
     */
    private $image;

    /**
     * @var Berkman\SlideshowBundle\Entity\Slideshow
     */
    private $slideshow;


    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set position
     *
     * @param integer $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    /**
     * Get position
     *
     * @return integer $position
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set image
     *
     * @param Berkman\SlideshowBundle\Entity\Image $image
     */
    public function setImage(Image $image)
    {
        $this->image = $image;
    }

    /**
     * Get image
     *
     * @return Berkman\SlideshowBundle\Entity\Image $image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set slideshow
     *
     * @param Berkman\SlideshowBundle\Entity\Slideshow $slideshow
     */
    public function setSlideshow(Slideshow $slideshow)
    {
        $this->slideshow = $slideshow;
        $this->position = count($this->getSlideshow()->getSlides()) + 1;
    }

    /**
     * Get slideshow
     *
     * @return Berkman\SlideshowBundle\Entity\Slideshow $slideshow
     */
    public function getSlideshow()
    {
        return $this->slideshow;
    }

    public function getThumbnailUrl()
    {
        return $this->getImage()->getThumbnailUrl();
    }

    /**
     * Create a slide from an Image
     *
     * @param Berkman\SlideshowBundle\Entity\Image $image
     */
    public function __construct(Image $image)
    {
        $this->setImage($image);
    }

    public function __call($functionName, $arguments)
    {
        return call_user_func_array(array($this->getImage(), $functionName), $arguments);
    }

}

src/Berkman/SlideshowBundle/Form/FinderType.php
<?php

namespace Berkman\SlideshowBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Doctrine\ORM\EntityRepository;

class FinderType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('keyword', null, array( 'label' => 'Keyword'))
            ->add('catalogs', 'entity', array(
                    'class' => 'Berkman\\SlideshowBundle\\Entity\\Catalog',
                    'property' => 'name',
                    'multiple' => true,
                    'expanded' => true,
                    'query_builder' => function(EntityRepository $er) { return $er->createQueryBuilder('c')->where('c.isSearchable = ?1')->setParameter(1, true); }
                )
            )
        ;
    }

    public function getName()
    {
        return 'finder';
    }
}

src/Berkman/SlideshowBundle/Form/ImportType.php
<?php

namespace Berkman\SlideshowBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class ImportType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('attachment', 'file')
        ;
    }

    public function getName()
    {
        return 'import';
    }
}

src/Berkman/SlideshowBundle/Controller/FinderController.php
<?php

namespace Berkman\SlideshowBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Cookie;
use Berkman\SlideshowBundle\Entity;
use Berkman\SlideshowBundle\Form\FinderType;
use Berkman\SlideshowBundle\Form\FinderResultsType;
use Berkman\SlideshowBundle\Form\ImportType;

/**
 * Finder controller.
 *
 * Notes:
 *   - Finder objects are now stuck in the session object instead of the database.
 *   - This necessitates certain changes:
 *        + IDs of objects (images, imageGroups) are going to have to be generated by something 
 *          other than the database
 *        + Catalog objects are going to be weird and wacky.  When persisting the images from
 *          the finder object, we'll have to pull the catalog from the database by ID and assign
 *          to the image and imageGroup objects.
 */
class FinderController extends Controller
{
    /**
     * Show the search form.
     *
     */
    public function indexAction()
    {
        $importForms = array();
        $request    = $this->getRequest();
        $em         = $this->getDoctrine()->getEntityManager();
        $catalogs   = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findAll();
        $slideshows = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->findAll();
        $finder     = new Entity\Finder($catalogs);
        $finderForm = $this->createForm(new FinderType(), $finder);
        $masterForm = $this->createForm(new ImportType());
        foreach ($catalogs as $catalog) {
            if ($catalog->hasCustomImporter()) {
                $importForms[$catalog->getId()] = $this->createForm(new ImportType())->createView();
            }
        }
        
        if ('POST' === $request->getMethod()) {
            $finderForm->bindRequest($request);

            if ($finderForm->isValid()) {
                $catalogIds = array();
                $catalogs = $finder->getCatalogs();
                foreach ($catalogs as $catalog) {
                    $catalogIds[] = $catalog->getId();
                }

                return $this->redirect($this->generateUrl('finder_show', array(
                    'catalogs'   => implode('_', $catalogIds),
                    'keyword' => $finder->getKeyword(),
                    'page'    => 1
                )));
            }
        }
        else {
            return $this->render('BerkmanSlideshowBundle:Finder:index.html.twig', array(
                'catalogs' => $catalogs,
                'slideshows' => $slideshows,
                'master_form' => $masterForm->createView(),
                'import_forms' => $importForms,
                'finderForm'  => $finderForm->createView()
            ));
        }

    }

    /**
     * Show the search results.
     *
     * @param string $catalogs  A '_' separated list of catalog IDs
     * @param string $keyword  The keyword for which to search
     * @param int $page  The page of search results to fetch
     *
     * @return Response
     *
     * Note: These next two functions pretty much repeat each other - they shouldn't
     */
    public function showAction($catalogs, $keyword, $page = 1)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $catalogs = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findBy(array(
            'id' => explode('_', $catalogs)
        ));
        if (!$catalogs) {
            throw $this->createNotFoundException('Unable to find Catalogs.');
        }

        $finder = $this->getFinder();
        $finder->setHierarchyStack(array($this->getRequest()->getUri()));
        $finder->setCatalogs($catalogs);
        $output = $finder->findResults($keyword, $page);

        $this->setFinder($finder);

        return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'imageGroups' => $finder->getCurrentImageGroupResults(),
        ));
    }

    /**
     * Show the results of a imageGroup search
     * 
     * @param string $imageGroupId  The id of the imageGroup to show
     * @param int $page  The page to fetch
     *
     * @return Response
     *
     */
    public function showImageGroupAction($imageGroupId, $page = 1)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $finder = $this->getFinder();
        if ($page == 1) {
            $finder->pushHierarchyStack($this->getRequest()->getUri());
        }

        $imageGroup = $finder->getImageGroup($imageGroupId);
        if (!$imageGroup) {
            throw $this->createNotFoundException('Unable to find imagegroup.');
        }

        $output = $finder->findImageGroupResults($imageGroup, $page);
        $this->setFinder($finder);

        return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'imageGroups' => $finder->getCurrentImageGroupResults(),
            'imageGroupId'=> $imageGroupId
        ));
    }

    /**
     * Handle the submission of the search results form
     * 
     * There are a few ways in which the form can be submitted:
     *   - Previous page button
     *   - Next page button
     *   - View ImageGroup button
     *   - Finish button
     * The selected images and imageGroup should be saved no matter the method
     *
     */
    public function submitAction()
    {
        $request   = $this->getRequest();
        $em        = $this->getDoctrine()->getEntityManager();
        $finder    = $this->getFinder();
        $response  = $this->redirect($this->generateUrl('slideshow_add_images'));

        $images = $request->get('images');
        if (!empty($images)) {
            foreach ($images as $image_id) {
                $finder->addSelectedImageResult($image_id); 
            }
        }

        $imageGroups = $request->get('imageGroups');
        if (!empty($imageGroups)) {
            foreach ($imageGroups as $imageGroup_id) {
                $images = $finder->getImageGroup($imageGroup_id)->getAllImages();
                foreach ($images as $image) {
                    $finder->addSelectedImageResult($finder->addImage($image));
                }
            }
        }

        if ($request->isXmlHttpRequest()) {
            return $this->render('BerkmanSlideshowBundle:Finder:addImages.json.twig', array(
                'finderImages' => count($finder->getSelectedImageResults())
            ));
        }

        $catalogIds = array();
        $catalogs = $finder->getCatalogs();
        foreach ($catalogs as $catalog) {
            $catalogIds[] = $catalog->getId();
        }

        if (in_array($request->get('action'), array('Next Page >', '< Previous Page'))) {
            $page = ($request->get('action') == 'Next Page >') ?
                $finder->getCurrentPage() + 1 : $finder->getCurrentPage() - 1;
            //This would mean we're browsing an image group
            if ($request->get('imageGroupId') != null) {
                $response = $this->redirect($this->generateUrl('finder_imageGroup', array(
                    'imageGroupId' => $request->get('imageGroupId'),
                    'page' => $page
                )));
            }
            else {
                $response = $this->redirect($this->generateUrl('finder_show', array(
                    'catalogs' => implode('_', $catalogIds),
                    'keyword' => $finder->getKeyword(),
                    'page' => $page
                )));
            }
        }
        elseif ($request->get('action') == 'Back') {
            $finder->popHierarchyStack();
            $uri = $finder->popHierarchyStack();
            $response = $this->redirect($uri);
        }
        elseif ($request->get('action') != 'Finish') {
            $response = $this->redirect($this->generateUrl('finder_imageGroup', array(
                'imageGroupId' => $request->get('action')
            )));
        }

        $this->setFinder($finder);

        return $response;
    }

    /**
     * Get the Finder object for the current session
     * or make a new one.
     *
     * @return Berkman\SlideshowBundle\Entity\Finder
     */
    private function getFinder()
    {
        $finder = $this->getRequest()->getSession()->get('finder');
        if (!$finder) {
            $finder = new Entity\Finder();
            $this->setFinder($finder);
        }

        return $finder;
    }

    /**
     * Assign some Finder object to the current session
     *
     * @param Berkman\SlideshowBundle\Entity\Finder $finder
     */
    private function setFinder(Entity\Finder $finder)
    {
        $this->getRequest()->getSession()->set('finder', $finder);
    }
}

src/Berkman/SlideshowBundle/Resources/views/Finder/addImages.json.twig
{{ finderImages }}

src/Berkman/SlideshowBundle/Resources/views/Finder/finder.html.twig
<form action="{{ path('finder_index') }}" method="post" {{ form_enctype(finderForm) }}>
    {{ form_errors(finderForm) }}

    <div>
        {{ form_label(finderForm.keyword) }}
        {{ form_errors(finderForm.keyword) }}
        {{ form_widget(finderForm.keyword) }}
        <button type="submit">SEARCH</button>
    </div>

    <div id="finder_catalogs">
    {% for catalog in finderForm.catalogs %}
        <div class="catalog-input">
        <div class="left-input">{{ form_widget(catalog) }}</div>
        {{ form_label(catalog) }}
        {{ form_errors(catalog) }}
        </div>
    {% endfor %}
    </div>

    {{ form_rest(finderForm) }}
</form>

src/Berkman/SlideshowBundle/Resources/views/Finder/index.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}

{% block title %}Spectacle - A Slideshow Machine for Harvard Library Images{% endblock %}

{% block body %}
    <div id="finder-tabs">
        <ul>
            <li><a href="#find-images">FIND IMAGES</a></li>
            <li><a href="#retrieve-images">DIRECT CATALOG IMPORT</a></li>
        </ul>

        <div id="find-images" class="centered">
            {% include 'BerkmanSlideshowBundle:Finder:finder.html.twig' %}
        </div>

        <div id="retrieve-images">
            {% include 'BerkmanSlideshowBundle:Slideshow:import.html.twig' %}
        </div>
    </div>

    <div id="desc">
        <p>Spectacle can be used to find images from Harvard library and museum collections, and incorporate them into an online slideshow. Each image is linked to descriptive information about the image and the Harvard collection within which it resides.</p>

        <p>All slideshows are accessible from a public gallery, and you may incorporate images from slideshows that others have created into one of your own.</p>
    </div>

    <div id="slideshow-tabs">
        <ul>
            <li><a href="#all-slideshows">BROWSE SLIDESHOWS</a></li>
            <li><a href="#my-slideshows">MY SLIDESHOWS</a></li>
        </ul>

        <div id="all-slideshows" class="block-container fancy-scroll">
            {% if slideshows is empty %}
                No public slideshows exist!  Help us out and make one.  I suggest searching for &quot;kitten&quot;.
            {% else %}
            <ul class="slideshows">
                {% for slideshow in slideshows %}
                    {% if slideshow.published %}
                    <li class="slideshow">
                        <a href="{{ path('slideshow_show', { 'id': slideshow.id }) }}">
                            {% if slideshow.slides[0] is defined %}
                            <img src="{{ slideshow.slides[0].thumbnailUrl }}" alt="{{ slideshow.id }}" />
                            <div class="slideshow-title">{{ slideshow.name }}</div>
                            <div class="slideshow-author">by {{ slideshow.person.username }}</div>
                            {% endif %}
                        </a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div id="my-slideshows" class="block-container fancy-scroll">
            {% if app.user.slideshows is defined and app.user.slideshows is not empty %}
            <ul class="slideshows">
                {% for slideshow in app.user.slideshows %}
                <li class="slideshow">
                    <a href="{{ path('slideshow_show', { 'id': slideshow.id }) }}">
                        {% if slideshow.slides[0] is defined %}
                        <img src="{{ slideshow.slides[0].image.thumbnailUrl }}" alt="{{ slideshow.id }}" />
                        <div class="slideshow-title">{{ slideshow.name }}</div>
                        <div class="slideshow-author">by {{ slideshow.person.username }}</div>
                        {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <p>Either you aren&apos;t logged in, or you don&apos;t have any slideshows yet.  Get on it.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts 'js/finder-index.js' %}
		<script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/Berkman/SlideshowBundle/Resources/views/Finder/show.html.twig
{% extends 'BerkmanSlideshowBundle::layout.html.twig' %}
{% import "BerkmanSlideshowBundle::macros.html.twig" as macros %}

{% block title %}Spectacle - Page {{ finder.currentPage }} Results for "{{ finder.keyword }}"{% endblock %}

{% block body %}

<div id="finder-results-tabs">
    <ul>
        <li><a href="#image-result-container">IMAGE RESULTS</a></li>
        {% if imageGroups|length > 0 %}
        <li><a href="#image-group-result-container">IMAGE GROUP RESULTS</a></li>
        {% endif %}
    </ul> 
    {% if finder.totalResults > 0 %}
    <form action="{{ path('finder_submit') }}" method="post" {# form_enctype(form) #}>
        <div class="result-container" id="image-result-container">
            <h2>
                {{ finder.totalResults }} results for &quot;{{ finder.keyword }}&quot; &ndash; Page {{ finder.currentPage }} of {{ finder.totalPages }}
            </h2>
            {% if images|length > 0 or imageGroups|length > 0 %}
                {% javascripts 'js/finder.js' %}
                    <script type="text/javascript" src="{{ asset_url }}"></script>
                {% endjavascripts %}
                <script>
                    var ajaxUrl  = "{{ path('finder_submit') }}",
                    {% image 'images/loading.gif' %}
                        loadingImage = $('<img style="border:0" src="{{ asset_url }}" alt="Loading" />');
                    {% endimage %}
                </script>
            {% endif %}
            
            {% if images|length > 0 %}
            {{ macros.show_images(images, 'ul', null, 'Add to slideshow', 'results-container') }}
            {% endif %}
            <div class="submit-buttons">
                <span class="left col">
                    {% if finder.currentPage > 1 %}
                    <input type="submit" id="previous-page" name="action" value="&lt; Previous Page" />
                    {% endif %}
                </span>
                <span class="center col">
                    {% if imageGroupId is defined %}
                        <input type="submit" name="action" value="Back" />
                        <input type="hidden" name="imageGroupId" value="{{ imageGroupId }}" />
                    {% endif %}
                    <input type="submit" id="finish-search" name="action" value="Finish" />
                </span>
                <span class="right col">
                    {% if finder.currentPage < finder.totalPages %}
                    <input type="submit" id="next-page" name="action" value="Next Page &gt;" />
                    {% endif %}
                </span>
            </div>
        </div>

        {% if imageGroups|length > 0 %}
        <div class="result-container" id="image-group-result-container">
            <h2>
                {{ finder.totalResults }} results for &quot;{{ finder.keyword }}&quot; &ndash; Page {{ finder.currentPage }} of {{ finder.totalPages }}
            </h2>
            {{ macros.show_imageGroups(imageGroups, 'ul', null, 'Add to slideshow') }}
            <div class="submit-buttons">
                <span class="left col">
                    {% if finder.currentPage > 1 %}
                    <input type="submit" id="previous-page" name="action" value="&lt; Previous Page" />
                    {% endif %}
                </span>
                <span class="center col">
                    {% if imageGroupId is defined %}
                        <input type="submit" name="action" value="Back" />
                        <input type="hidden" name="imageGroupId" value="{{ imageGroupId }}" />
                    {% endif %}
                    <input type="submit" id="finish-search" name="action" value="Finish" />
                </span>
                <span class="right col">
                    {% if finder.currentPage < finder.totalPages %}
                    <input type="submit" id="next-page" name="action" value="Next Page &gt;" />
                    {% endif %}
                </span>
            </div>
        </div>
        {% endif %}
    </form> 
    {% else %}
        <div id="image-container">
            <p>Sorry, but your search did not return any results.</p>
            <a href="{{ path('BerkmanSlideshowBundle_homepage') }}" class="buttoned" title="Back to Home">Back to Home</a>
        </div>
    {% endif %}
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts 'js/finder-show.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}